travis:
  secure:
    BINSTAR_TOKEN: RbRPEb8WdAR7J2+84uum39v7i0jZTpLzXQwCPz3iVmwDEmoM3qxgT6w+p2RdxaFhxHwJ498lOUEYPnH5fQQkxCXanXuOhz/HlVvDwmbAY/JDfFTSefI9hiagnnbM1v3+aVUcJnQRjxsGy7BkcFBTQSCqRtfm2OjCEgU096w/wFmAVWZ9W6VjJhrlO5rwurn8i5y74FtYiJTqPucNpNk6BWFruR2xeTpi5LStCkGsWJM3sVgACT/il6zCEzopCguZgKs0DsnWXt23hM+mujHmvE9TM95pwZqqcXu6Ws3SCeQH13a4y+FVeCFnrNLaqVdLlDH6+FMhyHI99knhVdD6p0q0X0hD6g+8p3bwu0tGKwrO6/ZsCde+IeN7q6VxERdV6ln8KgVaXSuGwaljRZEHhaIK5PD3AsjePQf9y/Z1fyOqseIpehT3kZedA31PJaf47aXjgwo2mbf7p8aECmveDu6CrPOCFHlyCJFa7Zm0ksEcdnPf49DBxdIxevtyj+fbEeZhap4BXmhyOkudC2p08cWvG4M79CkcOpKjt8YMH9bRowdeZXT4JpiAr6W1mvKT/8u8YCs2CqOn2uTScK8pIxSBltb7NI6sDj3XudTCoXqqds9iSKf5JnyzQgP4OEbifNRBdQZL6FmoPYoHUcD+dXyyFEU0vXNbdWpI+mNQnu0=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
